source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
